version: "3"

services:
    app:
        image: cje3295/lgts:app
        env_file:
            - .env
        ports:
            - "8080:8080"
        volumes:
            - /tmp:/tmp

    nginx:
        image: cje3295/lgts:nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app